name: rahoma_customers
description: "Reham , the closest to my heart"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  cloud_firestore: ^4.16.0
  firebase_auth: ^4.19.0
  firebase_core: ^2.28.0
  animations: ^2.0.11
  audioplayers: ^6.0.0
  auto_size_text: ^3.0.0
  animated_button: ^0.2.0
  achievement_view: ^1.0.0
  animated_text_kit: ^4.2.2
  animated_splash_screen: ^1.3.0
  badges: ^3.0.2
  bottom_bar_page_transition: ^2.0.0
  collection: ^1.17.1
  card_swiper: ^3.0.1
  carousel_slider: ^4.1.1
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  flutter_spinkit: ^5.2.1
  flutter_slidable: ^3.1.0
  flutter_screenutil: ^5.9.0
  flutter_pw_validator: ^1.4.2
  flutter_native_splash: ^2.4.0
  font_awesome_flutter: ^10.7.0
  fluentui_system_icons: ^1.1.232
  flutter_staggered_animations: ^1.1.1
  flutter_plugin_android_lifecycle: ^2.0.17
  get: ^4.6.6
  google_nav_bar: ^5.0.6
  google_fonts: ^6.2.1
  hexcolor: ^3.0.1
  intl: ^0.19.0
  icons_plus: ^5.0.0
  lottie: ^3.1.0
  liquid_pull_to_refresh: ^3.0.1
  provider: ^6.1.2
  path: ^1.9.0
  rive: ^0.13.1
  sqflite: ^2.3.3
  shared_preferences: ^2.2.2
  sn_progress_dialog: ^1.1.4
  shape_of_view_null_safe: ^3.0.0
  smooth_page_indicator: ^1.0.0+2
  staggered_grid_view_flutter: ^0.0.4
  uuid: ^4.3.3
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/glasses/
    - assets/fonts/Dosis/
    - assets/json/
    - assets/images/
    - assets/riveAssets/
    - assets/images/inapp/
    - assets/sounds/

  fonts:
    - family: Dosis
      fonts:
        - asset: assets/fonts/Dosis/Dosis-Bold.ttf
        - asset: assets/fonts/Dosis/Dosis-ExtraBold.ttf
        - asset: assets/fonts/Dosis/Dosis-ExtraLight.ttf
        - asset: assets/fonts/Dosis/Dosis-Light.ttf
        - asset: assets/fonts/Dosis/Dosis-Medium.ttf
        - asset: assets/fonts/Dosis/Dosis-Regular.ttf
        - asset: assets/fonts/Dosis/Dosis-SemiBold.ttf
        - asset: assets/fonts/Dosis/Dosis-VariableFont_wght.ttf
          style: normal
          weight: 500
    - family: Monofett
      fonts:
        - asset: assets/fonts/Monofett-Regular.ttf
          style: normal

    - family: Explora
      fonts:
        - asset: assets/fonts/Explora-Regular.ttf
          style: normal

    - family: Limelight
      fonts:
        - asset: assets/fonts/Limelight-Regular.ttf
          style: normal
          weight: 100
    - family: EnglishSC
      fonts:
        - asset: assets/fonts/IMFellEnglishSC-Regular.ttf
          style: normal
          weight: 100

    - family: CinzelDecorative
      fonts:
        - asset: assets/fonts/CinzelDecorative-Black.ttf
        - asset: assets/fonts/CinzelDecorative-Bold.ttf
        - asset: assets/fonts/CinzelDecorative-Regular.ttf
          style: normal
          weight: 500

