// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMvMDD4dK99vg1g23EssZWqLdg3nPLMcU',
    appId: '1:804124653009:web:7310b2f171e746fd571cf0',
    messagingSenderId: '804124653009',
    projectId: 'vast-app-a6de2',
    authDomain: 'vast-app-a6de2.firebaseapp.com',
    storageBucket: 'vast-app-a6de2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTkxyuwcIQttX01ps3trG3bXx8LCc3TPY',
    appId: '1:804124653009:android:40a2e99e54d398ae571cf0',
    messagingSenderId: '804124653009',
    projectId: 'vast-app-a6de2',
    storageBucket: 'vast-app-a6de2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzn3-4l9OM24wD6yWtqcDRh6XhMrJ5YBU',
    appId: '1:804124653009:ios:ac74a2baede457db571cf0',
    messagingSenderId: '804124653009',
    projectId: 'vast-app-a6de2',
    storageBucket: 'vast-app-a6de2.appspot.com',
    iosBundleId: 'com.example.rahomaCustomers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzn3-4l9OM24wD6yWtqcDRh6XhMrJ5YBU',
    appId: '1:804124653009:ios:ac74a2baede457db571cf0',
    messagingSenderId: '804124653009',
    projectId: 'vast-app-a6de2',
    storageBucket: 'vast-app-a6de2.appspot.com',
    iosBundleId: 'com.example.rahomaCustomers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMvMDD4dK99vg1g23EssZWqLdg3nPLMcU',
    appId: '1:804124653009:web:0f01d6acc1ddc88b571cf0',
    messagingSenderId: '804124653009',
    projectId: 'vast-app-a6de2',
    authDomain: 'vast-app-a6de2.firebaseapp.com',
    storageBucket: 'vast-app-a6de2.appspot.com',
  );

}